#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltktDAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="LTDH")]
	public partial class LTDHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAdmin(tblAdmin instance);
    partial void UpdatetblAdmin(tblAdmin instance);
    partial void DeletetblAdmin(tblAdmin instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblAdvertisement(tblAdvertisement instance);
    partial void UpdatetblAdvertisement(tblAdvertisement instance);
    partial void DeletetblAdvertisement(tblAdvertisement instance);
    partial void InserttblContact(tblContact instance);
    partial void UpdatetblContact(tblContact instance);
    partial void DeletetblContact(tblContact instance);
    partial void InserttblContestForUniversity(tblContestForUniversity instance);
    partial void UpdatetblContestForUniversity(tblContestForUniversity instance);
    partial void DeletetblContestForUniversity(tblContestForUniversity instance);
    partial void InserttblControl(tblControl instance);
    partial void UpdatetblControl(tblControl instance);
    partial void DeletetblControl(tblControl instance);
    partial void InserttblEnglish(tblEnglish instance);
    partial void UpdatetblEnglish(tblEnglish instance);
    partial void DeletetblEnglish(tblEnglish instance);
    partial void InserttblInformatic(tblInformatic instance);
    partial void UpdatetblInformatic(tblInformatic instance);
    partial void DeletetblInformatic(tblInformatic instance);
    partial void InserttblNew(tblNew instance);
    partial void UpdatetblNew(tblNew instance);
    partial void DeletetblNew(tblNew instance);
    partial void InserttblStatistic(tblStatistic instance);
    partial void UpdatetblStatistic(tblStatistic instance);
    partial void DeletetblStatistic(tblStatistic instance);
    #endregion
		
		public LTDHDataContext() : 
				base(global::ltktDAO.Properties.Settings.Default.LTDHConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LTDHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTDHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTDHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTDHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAdmin> tblAdmins
		{
			get
			{
				return this.GetTable<tblAdmin>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblAdvertisement> tblAdvertisements
		{
			get
			{
				return this.GetTable<tblAdvertisement>();
			}
		}
		
		public System.Data.Linq.Table<tblContact> tblContacts
		{
			get
			{
				return this.GetTable<tblContact>();
			}
		}
		
		public System.Data.Linq.Table<tblContestForUniversity> tblContestForUniversities
		{
			get
			{
				return this.GetTable<tblContestForUniversity>();
			}
		}
		
		public System.Data.Linq.Table<tblControl> tblControls
		{
			get
			{
				return this.GetTable<tblControl>();
			}
		}
		
		public System.Data.Linq.Table<tblEnglish> tblEnglishes
		{
			get
			{
				return this.GetTable<tblEnglish>();
			}
		}
		
		public System.Data.Linq.Table<tblInformatic> tblInformatics
		{
			get
			{
				return this.GetTable<tblInformatic>();
			}
		}
		
		public System.Data.Linq.Table<tblNew> tblNews
		{
			get
			{
				return this.GetTable<tblNew>();
			}
		}
		
		public System.Data.Linq.Table<tblPermission> tblPermissions
		{
			get
			{
				return this.GetTable<tblPermission>();
			}
		}
		
		public System.Data.Linq.Table<tblStatistic> tblStatistics
		{
			get
			{
				return this.GetTable<tblStatistic>();
			}
		}
	}
	
	[Table(Name="dbo.tblAdmin")]
	public partial class tblAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Message;
		
		private bool _State;
		
		private string _Reason;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStateChanging(bool value);
    partial void OnStateChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    #endregion
		
		public tblAdmin()
		{
			OnCreated();
		}
		
		[Column(Storage="_Code", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[Column(Storage="_Message", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Bit NOT NULL")]
		public bool State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_Reason", DbType="NVarChar(500)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblUsers")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Username;
		
		private string _Password;
		
		private string _DisplayName;
		
		private string _Email;
		
		private bool _Sex;
		
		private bool _Type;
		
		private string _Role;
		
		private string _Permission;
		
		private int _State;
		
		private System.DateTime _RegisterDate;
		
		private System.Nullable<System.DateTime> _KIADate;
		
		private int _NumberOfArticles;
		
		private string _Note;
		
		private EntitySet<tblContestForUniversity> _tblContestForUniversities;
		
		private EntitySet<tblContestForUniversity> _tblContestForUniversities1;
		
		private EntitySet<tblEnglish> _tblEnglishes;
		
		private EntitySet<tblEnglish> _tblEnglishes1;
		
		private EntitySet<tblInformatic> _tblInformatics;
		
		private EntitySet<tblInformatic> _tblInformatics1;
		
		private EntitySet<tblNew> _tblNews;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSexChanging(bool value);
    partial void OnSexChanged();
    partial void OnTypeChanging(bool value);
    partial void OnTypeChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnPermissionChanging(string value);
    partial void OnPermissionChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnRegisterDateChanging(System.DateTime value);
    partial void OnRegisterDateChanged();
    partial void OnKIADateChanging(System.Nullable<System.DateTime> value);
    partial void OnKIADateChanged();
    partial void OnNumberOfArticlesChanging(int value);
    partial void OnNumberOfArticlesChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public tblUser()
		{
			this._tblContestForUniversities = new EntitySet<tblContestForUniversity>(new Action<tblContestForUniversity>(this.attach_tblContestForUniversities), new Action<tblContestForUniversity>(this.detach_tblContestForUniversities));
			this._tblContestForUniversities1 = new EntitySet<tblContestForUniversity>(new Action<tblContestForUniversity>(this.attach_tblContestForUniversities1), new Action<tblContestForUniversity>(this.detach_tblContestForUniversities1));
			this._tblEnglishes = new EntitySet<tblEnglish>(new Action<tblEnglish>(this.attach_tblEnglishes), new Action<tblEnglish>(this.detach_tblEnglishes));
			this._tblEnglishes1 = new EntitySet<tblEnglish>(new Action<tblEnglish>(this.attach_tblEnglishes1), new Action<tblEnglish>(this.detach_tblEnglishes1));
			this._tblInformatics = new EntitySet<tblInformatic>(new Action<tblInformatic>(this.attach_tblInformatics), new Action<tblInformatic>(this.detach_tblInformatics));
			this._tblInformatics1 = new EntitySet<tblInformatic>(new Action<tblInformatic>(this.attach_tblInformatics1), new Action<tblInformatic>(this.detach_tblInformatics1));
			this._tblNews = new EntitySet<tblNew>(new Action<tblNew>(this.attach_tblNews), new Action<tblNew>(this.detach_tblNews));
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Username", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="NChar(254) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_DisplayName", DbType="NVarChar(50)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Sex", DbType="Bit NOT NULL")]
		public bool Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[Column(Storage="_Type", DbType="Bit NOT NULL")]
		public bool Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Role", DbType="NVarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[Column(Storage="_Permission", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_RegisterDate", DbType="DateTime NOT NULL")]
		public System.DateTime RegisterDate
		{
			get
			{
				return this._RegisterDate;
			}
			set
			{
				if ((this._RegisterDate != value))
				{
					this.OnRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._RegisterDate = value;
					this.SendPropertyChanged("RegisterDate");
					this.OnRegisterDateChanged();
				}
			}
		}
		
		[Column(Storage="_KIADate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KIADate
		{
			get
			{
				return this._KIADate;
			}
			set
			{
				if ((this._KIADate != value))
				{
					this.OnKIADateChanging(value);
					this.SendPropertyChanging();
					this._KIADate = value;
					this.SendPropertyChanged("KIADate");
					this.OnKIADateChanged();
				}
			}
		}
		
		[Column(Storage="_NumberOfArticles", DbType="Int NOT NULL")]
		public int NumberOfArticles
		{
			get
			{
				return this._NumberOfArticles;
			}
			set
			{
				if ((this._NumberOfArticles != value))
				{
					this.OnNumberOfArticlesChanging(value);
					this.SendPropertyChanging();
					this._NumberOfArticles = value;
					this.SendPropertyChanged("NumberOfArticles");
					this.OnNumberOfArticlesChanged();
				}
			}
		}
		
		[Column(Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[Association(Name="tblUser_tblContestForUniversity", Storage="_tblContestForUniversities", ThisKey="Username", OtherKey="Author")]
		public EntitySet<tblContestForUniversity> tblContestForUniversities
		{
			get
			{
				return this._tblContestForUniversities;
			}
			set
			{
				this._tblContestForUniversities.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblContestForUniversity1", Storage="_tblContestForUniversities1", ThisKey="Username", OtherKey="Checker")]
		public EntitySet<tblContestForUniversity> tblContestForUniversities1
		{
			get
			{
				return this._tblContestForUniversities1;
			}
			set
			{
				this._tblContestForUniversities1.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblEnglish", Storage="_tblEnglishes", ThisKey="Username", OtherKey="Author")]
		public EntitySet<tblEnglish> tblEnglishes
		{
			get
			{
				return this._tblEnglishes;
			}
			set
			{
				this._tblEnglishes.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblEnglish1", Storage="_tblEnglishes1", ThisKey="Username", OtherKey="Checker")]
		public EntitySet<tblEnglish> tblEnglishes1
		{
			get
			{
				return this._tblEnglishes1;
			}
			set
			{
				this._tblEnglishes1.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblInformatic", Storage="_tblInformatics", ThisKey="Username", OtherKey="Author")]
		public EntitySet<tblInformatic> tblInformatics
		{
			get
			{
				return this._tblInformatics;
			}
			set
			{
				this._tblInformatics.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblInformatic1", Storage="_tblInformatics1", ThisKey="Username", OtherKey="Checker")]
		public EntitySet<tblInformatic> tblInformatics1
		{
			get
			{
				return this._tblInformatics1;
			}
			set
			{
				this._tblInformatics1.Assign(value);
			}
		}
		
		[Association(Name="tblUser_tblNew", Storage="_tblNews", ThisKey="Username", OtherKey="Author")]
		public EntitySet<tblNew> tblNews
		{
			get
			{
				return this._tblNews;
			}
			set
			{
				this._tblNews.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblContestForUniversities(tblContestForUniversity entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblContestForUniversities(tblContestForUniversity entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
		
		private void attach_tblContestForUniversities1(tblContestForUniversity entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = this;
		}
		
		private void detach_tblContestForUniversities1(tblContestForUniversity entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = null;
		}
		
		private void attach_tblEnglishes(tblEnglish entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblEnglishes(tblEnglish entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
		
		private void attach_tblEnglishes1(tblEnglish entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = this;
		}
		
		private void detach_tblEnglishes1(tblEnglish entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = null;
		}
		
		private void attach_tblInformatics(tblInformatic entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblInformatics(tblInformatic entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
		
		private void attach_tblInformatics1(tblInformatic entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = this;
		}
		
		private void detach_tblInformatics1(tblInformatic entity)
		{
			this.SendPropertyChanging();
			entity.tblUser1 = null;
		}
		
		private void attach_tblNews(tblNew entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblNews(tblNew entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
	}
	
	[Table(Name="dbo.tblAdvertisement")]
	public partial class tblAdvertisement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Code;
		
		private string _Company;
		
		private string _Address;
		
		private string _Email;
		
		private string _Phone;
		
		private System.Nullable<System.DateTime> _fromDate;
		
		private System.Nullable<System.DateTime> _toDate;
		
		private int _Price;
		
		private string _Location;
		
		private string _Description;
		
		private int _State;
		
		private int _ClickCount;
		
		private string _NavigateUrl;
		
		private string _Size;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnfromDateChanging(System.Nullable<System.DateTime> value);
    partial void OnfromDateChanged();
    partial void OntoDateChanging(System.Nullable<System.DateTime> value);
    partial void OntoDateChanged();
    partial void OnPriceChanging(int value);
    partial void OnPriceChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnClickCountChanging(int value);
    partial void OnClickCountChanged();
    partial void OnNavigateUrlChanging(string value);
    partial void OnNavigateUrlChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    #endregion
		
		public tblAdvertisement()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Code", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[Column(Storage="_Company", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[Column(Storage="_Address", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Phone", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_fromDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fromDate
		{
			get
			{
				return this._fromDate;
			}
			set
			{
				if ((this._fromDate != value))
				{
					this.OnfromDateChanging(value);
					this.SendPropertyChanging();
					this._fromDate = value;
					this.SendPropertyChanged("fromDate");
					this.OnfromDateChanged();
				}
			}
		}
		
		[Column(Storage="_toDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> toDate
		{
			get
			{
				return this._toDate;
			}
			set
			{
				if ((this._toDate != value))
				{
					this.OntoDateChanging(value);
					this.SendPropertyChanging();
					this._toDate = value;
					this.SendPropertyChanged("toDate");
					this.OntoDateChanged();
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Int NOT NULL")]
		public int Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[Column(Storage="_Location", DbType="NChar(254) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_ClickCount", DbType="Int NOT NULL")]
		public int ClickCount
		{
			get
			{
				return this._ClickCount;
			}
			set
			{
				if ((this._ClickCount != value))
				{
					this.OnClickCountChanging(value);
					this.SendPropertyChanging();
					this._ClickCount = value;
					this.SendPropertyChanged("ClickCount");
					this.OnClickCountChanged();
				}
			}
		}
		
		[Column(Storage="_NavigateUrl", DbType="NVarChar(254)")]
		public string NavigateUrl
		{
			get
			{
				return this._NavigateUrl;
			}
			set
			{
				if ((this._NavigateUrl != value))
				{
					this.OnNavigateUrlChanging(value);
					this.SendPropertyChanging();
					this._NavigateUrl = value;
					this.SendPropertyChanged("NavigateUrl");
					this.OnNavigateUrlChanged();
				}
			}
		}
		
		[Column(Storage="_Size", DbType="NChar(20)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblContact")]
	public partial class tblContact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _EmailFrom;
		
		private string _EmailTo;
		
		private string _Subject;
		
		private string _Contents;
		
		private System.DateTime _Posted;
		
		private bool _isRead;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmailFromChanging(string value);
    partial void OnEmailFromChanged();
    partial void OnEmailToChanging(string value);
    partial void OnEmailToChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnPostedChanging(System.DateTime value);
    partial void OnPostedChanged();
    partial void OnisReadChanging(bool value);
    partial void OnisReadChanged();
    #endregion
		
		public tblContact()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_EmailFrom", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this.OnEmailFromChanging(value);
					this.SendPropertyChanging();
					this._EmailFrom = value;
					this.SendPropertyChanged("EmailFrom");
					this.OnEmailFromChanged();
				}
			}
		}
		
		[Column(Storage="_EmailTo", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string EmailTo
		{
			get
			{
				return this._EmailTo;
			}
			set
			{
				if ((this._EmailTo != value))
				{
					this.OnEmailToChanging(value);
					this.SendPropertyChanging();
					this._EmailTo = value;
					this.SendPropertyChanged("EmailTo");
					this.OnEmailToChanged();
				}
			}
		}
		
		[Column(Storage="_Subject", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[Column(Storage="_Contents", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this.OnPostedChanging(value);
					this.SendPropertyChanging();
					this._Posted = value;
					this.SendPropertyChanged("Posted");
					this.OnPostedChanged();
				}
			}
		}
		
		[Column(Storage="_isRead", DbType="Bit NOT NULL")]
		public bool isRead
		{
			get
			{
				return this._isRead;
			}
			set
			{
				if ((this._isRead != value))
				{
					this.OnisReadChanging(value);
					this.SendPropertyChanging();
					this._isRead = value;
					this.SendPropertyChanged("isRead");
					this.OnisReadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblContestForUniversity")]
	public partial class tblContestForUniversity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private string _Contents;
		
		private string _Author;
		
		private System.DateTime _Posted;
		
		private int _State;
		
		private bool _isUniversity;
		
		private int _Branch;
		
		private int _Year;
		
		private string _Thumbnail;
		
		private string _Solving;
		
		private int _Point;
		
		private string _Tag;
		
		private string _Location;
		
		private string _Subject;
		
		private string _Comment;
		
		private int _Score;
		
		private string _Checker;
		
		private string _HtmlPreview;
		
		private string _HtmlEmbedLink;
		
		private bool _StickyFlg;
		
		private EntityRef<tblUser> _tblUser;
		
		private EntityRef<tblUser> _tblUser1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPostedChanging(System.DateTime value);
    partial void OnPostedChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnisUniversityChanging(bool value);
    partial void OnisUniversityChanged();
    partial void OnBranchChanging(int value);
    partial void OnBranchChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnSolvingChanging(string value);
    partial void OnSolvingChanged();
    partial void OnPointChanging(int value);
    partial void OnPointChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    partial void OnCheckerChanging(string value);
    partial void OnCheckerChanged();
    partial void OnHtmlPreviewChanging(string value);
    partial void OnHtmlPreviewChanged();
    partial void OnHtmlEmbedLinkChanging(string value);
    partial void OnHtmlEmbedLinkChanged();
    partial void OnStickyFlgChanging(bool value);
    partial void OnStickyFlgChanged();
    #endregion
		
		public tblContestForUniversity()
		{
			this._tblUser = default(EntityRef<tblUser>);
			this._tblUser1 = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Contents", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[Column(Storage="_Author", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this.OnPostedChanging(value);
					this.SendPropertyChanging();
					this._Posted = value;
					this.SendPropertyChanged("Posted");
					this.OnPostedChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_isUniversity", DbType="Bit NOT NULL")]
		public bool isUniversity
		{
			get
			{
				return this._isUniversity;
			}
			set
			{
				if ((this._isUniversity != value))
				{
					this.OnisUniversityChanging(value);
					this.SendPropertyChanging();
					this._isUniversity = value;
					this.SendPropertyChanged("isUniversity");
					this.OnisUniversityChanged();
				}
			}
		}
		
		[Column(Storage="_Branch", DbType="Int NOT NULL")]
		public int Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		[Column(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[Column(Storage="_Thumbnail", DbType="NChar(254)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[Column(Storage="_Solving", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Solving
		{
			get
			{
				return this._Solving;
			}
			set
			{
				if ((this._Solving != value))
				{
					this.OnSolvingChanging(value);
					this.SendPropertyChanging();
					this._Solving = value;
					this.SendPropertyChanged("Solving");
					this.OnSolvingChanged();
				}
			}
		}
		
		[Column(Storage="_Point", DbType="Int NOT NULL")]
		public int Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this.OnPointChanging(value);
					this.SendPropertyChanging();
					this._Point = value;
					this.SendPropertyChanged("Point");
					this.OnPointChanged();
				}
			}
		}
		
		[Column(Storage="_Tag", DbType="NVarChar(254)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[Column(Storage="_Location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[Column(Storage="_Subject", DbType="NVarChar(20)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[Column(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[Column(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[Column(Storage="_Checker", DbType="NChar(20)")]
		public string Checker
		{
			get
			{
				return this._Checker;
			}
			set
			{
				if ((this._Checker != value))
				{
					if (this._tblUser1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckerChanging(value);
					this.SendPropertyChanging();
					this._Checker = value;
					this.SendPropertyChanged("Checker");
					this.OnCheckerChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlPreview", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string HtmlPreview
		{
			get
			{
				return this._HtmlPreview;
			}
			set
			{
				if ((this._HtmlPreview != value))
				{
					this.OnHtmlPreviewChanging(value);
					this.SendPropertyChanging();
					this._HtmlPreview = value;
					this.SendPropertyChanged("HtmlPreview");
					this.OnHtmlPreviewChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlEmbedLink", DbType="NChar(254)")]
		public string HtmlEmbedLink
		{
			get
			{
				return this._HtmlEmbedLink;
			}
			set
			{
				if ((this._HtmlEmbedLink != value))
				{
					this.OnHtmlEmbedLinkChanging(value);
					this.SendPropertyChanging();
					this._HtmlEmbedLink = value;
					this.SendPropertyChanged("HtmlEmbedLink");
					this.OnHtmlEmbedLinkChanged();
				}
			}
		}
		
		[Column(Storage="_StickyFlg", DbType="Bit NOT NULL")]
		public bool StickyFlg
		{
			get
			{
				return this._StickyFlg;
			}
			set
			{
				if ((this._StickyFlg != value))
				{
					this.OnStickyFlgChanging(value);
					this.SendPropertyChanging();
					this._StickyFlg = value;
					this.SendPropertyChanged("StickyFlg");
					this.OnStickyFlgChanged();
				}
			}
		}
		
		[Association(Name="tblUser_tblContestForUniversity", Storage="_tblUser", ThisKey="Author", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblContestForUniversities.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblContestForUniversities.Add(this);
						this._Author = value.Username;
					}
					else
					{
						this._Author = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		[Association(Name="tblUser_tblContestForUniversity1", Storage="_tblUser1", ThisKey="Checker", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser1
		{
			get
			{
				return this._tblUser1.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser1.Entity;
				if (((previousValue != value) 
							|| (this._tblUser1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser1.Entity = null;
						previousValue.tblContestForUniversities1.Remove(this);
					}
					this._tblUser1.Entity = value;
					if ((value != null))
					{
						value.tblContestForUniversities1.Add(this);
						this._Checker = value.Username;
					}
					else
					{
						this._Checker = default(string);
					}
					this.SendPropertyChanged("tblUser1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblControl")]
	public partial class tblControl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Name;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public tblControl()
		{
			OnCreated();
		}
		
		[Column(Storage="_Code", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NVarChar(500)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblEnglish")]
	public partial class tblEnglish : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private int _Type;
		
		private string _Contents;
		
		private string _Thumbnail;
		
		private string _Author;
		
		private System.DateTime _Posted;
		
		private int _State;
		
		private int _Point;
		
		private string _Tag;
		
		private string _Location;
		
		private int _Score;
		
		private string _Comment;
		
		private string _Checker;
		
		private string _HtmlPreview;
		
		private string _HtmlEmbedLink;
		
		private int _Class;
		
		private bool _StickyFlg;
		
		private EntityRef<tblUser> _tblUser;
		
		private EntityRef<tblUser> _tblUser1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPostedChanging(System.DateTime value);
    partial void OnPostedChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnPointChanging(int value);
    partial void OnPointChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCheckerChanging(string value);
    partial void OnCheckerChanged();
    partial void OnHtmlPreviewChanging(string value);
    partial void OnHtmlPreviewChanged();
    partial void OnHtmlEmbedLinkChanging(string value);
    partial void OnHtmlEmbedLinkChanged();
    partial void OnClassChanging(int value);
    partial void OnClassChanged();
    partial void OnStickyFlgChanging(bool value);
    partial void OnStickyFlgChanged();
    #endregion
		
		public tblEnglish()
		{
			this._tblUser = default(EntityRef<tblUser>);
			this._tblUser1 = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Contents", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[Column(Storage="_Thumbnail", DbType="NChar(254)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[Column(Storage="_Author", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this.OnPostedChanging(value);
					this.SendPropertyChanging();
					this._Posted = value;
					this.SendPropertyChanged("Posted");
					this.OnPostedChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_Point", DbType="Int NOT NULL")]
		public int Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this.OnPointChanging(value);
					this.SendPropertyChanging();
					this._Point = value;
					this.SendPropertyChanged("Point");
					this.OnPointChanged();
				}
			}
		}
		
		[Column(Storage="_Tag", DbType="NVarChar(254)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[Column(Storage="_Location", DbType="NVarChar(200)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[Column(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[Column(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[Column(Storage="_Checker", DbType="NChar(20)")]
		public string Checker
		{
			get
			{
				return this._Checker;
			}
			set
			{
				if ((this._Checker != value))
				{
					if (this._tblUser1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckerChanging(value);
					this.SendPropertyChanging();
					this._Checker = value;
					this.SendPropertyChanged("Checker");
					this.OnCheckerChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlPreview", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string HtmlPreview
		{
			get
			{
				return this._HtmlPreview;
			}
			set
			{
				if ((this._HtmlPreview != value))
				{
					this.OnHtmlPreviewChanging(value);
					this.SendPropertyChanging();
					this._HtmlPreview = value;
					this.SendPropertyChanged("HtmlPreview");
					this.OnHtmlPreviewChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlEmbedLink", DbType="NChar(254)")]
		public string HtmlEmbedLink
		{
			get
			{
				return this._HtmlEmbedLink;
			}
			set
			{
				if ((this._HtmlEmbedLink != value))
				{
					this.OnHtmlEmbedLinkChanging(value);
					this.SendPropertyChanging();
					this._HtmlEmbedLink = value;
					this.SendPropertyChanged("HtmlEmbedLink");
					this.OnHtmlEmbedLinkChanged();
				}
			}
		}
		
		[Column(Storage="_Class", DbType="Int NOT NULL")]
		public int Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[Column(Storage="_StickyFlg", DbType="Bit NOT NULL")]
		public bool StickyFlg
		{
			get
			{
				return this._StickyFlg;
			}
			set
			{
				if ((this._StickyFlg != value))
				{
					this.OnStickyFlgChanging(value);
					this.SendPropertyChanging();
					this._StickyFlg = value;
					this.SendPropertyChanged("StickyFlg");
					this.OnStickyFlgChanged();
				}
			}
		}
		
		[Association(Name="tblUser_tblEnglish", Storage="_tblUser", ThisKey="Author", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblEnglishes.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblEnglishes.Add(this);
						this._Author = value.Username;
					}
					else
					{
						this._Author = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		[Association(Name="tblUser_tblEnglish1", Storage="_tblUser1", ThisKey="Checker", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser1
		{
			get
			{
				return this._tblUser1.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser1.Entity;
				if (((previousValue != value) 
							|| (this._tblUser1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser1.Entity = null;
						previousValue.tblEnglishes1.Remove(this);
					}
					this._tblUser1.Entity = value;
					if ((value != null))
					{
						value.tblEnglishes1.Add(this);
						this._Checker = value.Username;
					}
					else
					{
						this._Checker = default(string);
					}
					this.SendPropertyChanged("tblUser1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblInformatics")]
	public partial class tblInformatic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private int _Type;
		
		private string _Chapeau;
		
		private string _Contents;
		
		private string _Thumbnail;
		
		private string _Location;
		
		private string _Author;
		
		private System.DateTime _Posted;
		
		private int _State;
		
		private int _Leitmotif;
		
		private int _Score;
		
		private int _Point;
		
		private string _Tag;
		
		private string _Comment;
		
		private string _Checker;
		
		private string _HtmlPreview;
		
		private string _HtmlEmbedLink;
		
		private bool _StickyFlg;
		
		private EntityRef<tblUser> _tblUser;
		
		private EntityRef<tblUser> _tblUser1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnChapeauChanging(string value);
    partial void OnChapeauChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPostedChanging(System.DateTime value);
    partial void OnPostedChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnLeitmotifChanging(int value);
    partial void OnLeitmotifChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    partial void OnPointChanging(int value);
    partial void OnPointChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCheckerChanging(string value);
    partial void OnCheckerChanged();
    partial void OnHtmlPreviewChanging(string value);
    partial void OnHtmlPreviewChanged();
    partial void OnHtmlEmbedLinkChanging(string value);
    partial void OnHtmlEmbedLinkChanged();
    partial void OnStickyFlgChanging(bool value);
    partial void OnStickyFlgChanged();
    #endregion
		
		public tblInformatic()
		{
			this._tblUser = default(EntityRef<tblUser>);
			this._tblUser1 = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Chapeau", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Chapeau
		{
			get
			{
				return this._Chapeau;
			}
			set
			{
				if ((this._Chapeau != value))
				{
					this.OnChapeauChanging(value);
					this.SendPropertyChanging();
					this._Chapeau = value;
					this.SendPropertyChanged("Chapeau");
					this.OnChapeauChanged();
				}
			}
		}
		
		[Column(Storage="_Contents", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[Column(Storage="_Thumbnail", DbType="NChar(254)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[Column(Storage="_Location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[Column(Storage="_Author", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime NOT NULL")]
		public System.DateTime Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this.OnPostedChanging(value);
					this.SendPropertyChanging();
					this._Posted = value;
					this.SendPropertyChanged("Posted");
					this.OnPostedChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_Leitmotif", DbType="Int NOT NULL")]
		public int Leitmotif
		{
			get
			{
				return this._Leitmotif;
			}
			set
			{
				if ((this._Leitmotif != value))
				{
					this.OnLeitmotifChanging(value);
					this.SendPropertyChanging();
					this._Leitmotif = value;
					this.SendPropertyChanged("Leitmotif");
					this.OnLeitmotifChanged();
				}
			}
		}
		
		[Column(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[Column(Storage="_Point", DbType="Int NOT NULL")]
		public int Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this.OnPointChanging(value);
					this.SendPropertyChanging();
					this._Point = value;
					this.SendPropertyChanged("Point");
					this.OnPointChanged();
				}
			}
		}
		
		[Column(Storage="_Tag", DbType="NVarChar(254)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[Column(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[Column(Storage="_Checker", DbType="NChar(20)")]
		public string Checker
		{
			get
			{
				return this._Checker;
			}
			set
			{
				if ((this._Checker != value))
				{
					if (this._tblUser1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckerChanging(value);
					this.SendPropertyChanging();
					this._Checker = value;
					this.SendPropertyChanged("Checker");
					this.OnCheckerChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlPreview", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string HtmlPreview
		{
			get
			{
				return this._HtmlPreview;
			}
			set
			{
				if ((this._HtmlPreview != value))
				{
					this.OnHtmlPreviewChanging(value);
					this.SendPropertyChanging();
					this._HtmlPreview = value;
					this.SendPropertyChanged("HtmlPreview");
					this.OnHtmlPreviewChanged();
				}
			}
		}
		
		[Column(Storage="_HtmlEmbedLink", DbType="NChar(254)")]
		public string HtmlEmbedLink
		{
			get
			{
				return this._HtmlEmbedLink;
			}
			set
			{
				if ((this._HtmlEmbedLink != value))
				{
					this.OnHtmlEmbedLinkChanging(value);
					this.SendPropertyChanging();
					this._HtmlEmbedLink = value;
					this.SendPropertyChanged("HtmlEmbedLink");
					this.OnHtmlEmbedLinkChanged();
				}
			}
		}
		
		[Column(Storage="_StickyFlg", DbType="Bit NOT NULL")]
		public bool StickyFlg
		{
			get
			{
				return this._StickyFlg;
			}
			set
			{
				if ((this._StickyFlg != value))
				{
					this.OnStickyFlgChanging(value);
					this.SendPropertyChanging();
					this._StickyFlg = value;
					this.SendPropertyChanged("StickyFlg");
					this.OnStickyFlgChanged();
				}
			}
		}
		
		[Association(Name="tblUser_tblInformatic", Storage="_tblUser", ThisKey="Author", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblInformatics.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblInformatics.Add(this);
						this._Author = value.Username;
					}
					else
					{
						this._Author = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		[Association(Name="tblUser_tblInformatic1", Storage="_tblUser1", ThisKey="Checker", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser1
		{
			get
			{
				return this._tblUser1.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser1.Entity;
				if (((previousValue != value) 
							|| (this._tblUser1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser1.Entity = null;
						previousValue.tblInformatics1.Remove(this);
					}
					this._tblUser1.Entity = value;
					if ((value != null))
					{
						value.tblInformatics1.Add(this);
						this._Checker = value.Username;
					}
					else
					{
						this._Checker = default(string);
					}
					this.SendPropertyChanged("tblUser1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblNews")]
	public partial class tblNew : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private string _Chapaeu;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _Posted;
		
		private string _Author;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnChapaeuChanging(string value);
    partial void OnChapaeuChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnPostedChanging(System.Nullable<System.DateTime> value);
    partial void OnPostedChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    #endregion
		
		public tblNew()
		{
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Chapaeu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Chapaeu
		{
			get
			{
				return this._Chapaeu;
			}
			set
			{
				if ((this._Chapaeu != value))
				{
					this.OnChapaeuChanging(value);
					this.SendPropertyChanging();
					this._Chapaeu = value;
					this.SendPropertyChanged("Chapaeu");
					this.OnChapaeuChanged();
				}
			}
		}
		
		[Column(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[Column(Storage="_Posted", DbType="DateTime")]
		public System.Nullable<System.DateTime> Posted
		{
			get
			{
				return this._Posted;
			}
			set
			{
				if ((this._Posted != value))
				{
					this.OnPostedChanging(value);
					this.SendPropertyChanging();
					this._Posted = value;
					this.SendPropertyChanged("Posted");
					this.OnPostedChanged();
				}
			}
		}
		
		[Column(Storage="_Author", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[Association(Name="tblUser_tblNew", Storage="_tblUser", ThisKey="Author", OtherKey="Username", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblNews.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblNews.Add(this);
						this._Author = value.Username;
					}
					else
					{
						this._Author = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tblPermission")]
	public partial class tblPermission
	{
		
		private string _Code;
		
		private string _Name;
		
		private int _Value;
		
		public tblPermission()
		{
		}
		
		[Column(Storage="_Code", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Value", DbType="Int NOT NULL")]
		public int Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.tblStatistic")]
	public partial class tblStatistic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Name;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public tblStatistic()
		{
			OnCreated();
		}
		
		[Column(Storage="_Code", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NChar(254) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
